### ISSUE TITLE
Possible to change the game window size within the vnc browser?

### ISSUE THREAD

**Issue by traw1234** [openai/universe#105]
This isn't a bug as much as a question: is it possible to change the window size of the game in the vnc browser. When using the slither.io env, it is extremely difficult to do any image processing due to the leaderboards section taking up a quarter of the screen. Its because of the small window size that it auto scales to take up much of the space. This can be fixed by either making the game window bigger (cropping it doesn't help, just makes it bigger, it needs to actually take up more space within the browser) or zooming out in the browser (scaling it to, say 25%). I was wondering if this is possible/how to do it in universe.

**Comment by tlbtlbtlb** [comment]
Humans can play it pretty well at that resolution and with the leaderboard (we've seen many 6000 point games, playing that exact environment through VNC) so we'll probably keep it that way. We did make an easier version though: Try `gym.make('internet.SlitherIONoSkins-v0')`, which both drops the leaderboard and makes all the other snakes the same color (otherwise, the dark gray ones are hard to see.) Of course, the world will be more impressed with high scores on the full versions, but the easy version is easier to experiment with.

BTW, if you're working on Slither, be aware that since it's playing live against people, the time window from around 1am to 5am Pacific is different because the games aren't full. Although you get killed less often, there is also less food so scores tend to be lower.

**Comment by traw1234** [comment]
Thanks, I didn't realize that there was another env for that. I guess that does make sense that humans can do it so it should stay the same.
