### ISSUE TITLE
Set universe not to be real-time, so as to be utilized as distributing compution

### ISSUE THREAD

**Issue by syhdog** [openai/universe#123]
Since the computing resources on a single machine is limited, even for a 40 threads server. I am using universe to separate environment running and agent. Five machines(8 cores), running docker containers of environment, each of them running 8 containers without any pressure on the CPU, and a server(40 cores) running the agent with 40 workers. All machine are in a high speed local network.
It turns out that the internet lag is a big problem. By doing this, I only intend to distribute the computing pressure by separating environment and agent, so the environment does not have to be real time. Is there anyway to config the universe to be none real-time(only step forward if receive a action from agent). Or if you can release a docker image of none real-time universe.
Then agent I am developing is quite special, which in need for more than 100 workers, so the computing distribution in need.

**Comment by tlbtlbtlb** [comment]
There's no fully general solution for slowing down Universe envs. The synchronous ones (like Pong) run at any speed, but flashgames environments are hard because each game engine gets timing from the OS in various ways.

It might work better to distribute the workers among multiple machines. If you're using universe-starter-agent, the cluster is defined [here](https://github.com/openai/universe-starter-agent/blob/master/worker.py#L87). Right now it sets all the hosts to `127.0.0.1`, but you can distribute them among multiple machines by using the right IP addresses for each. You probably want to modify the worker to take the `cluster_spec` on the command line, and generate the `cluster_spec` in the driver (`trainer.py`) so you can also start the worker on the right machine.
