### ISSUE TITLE
NES games in openai universe 

### ISSUE THREAD

**Issue by nojvek** [openai/universe#150]
Any chance to support NES games using pyNES like atari_py?

**Comment by yashpatel5400** [comment]
Gonna try adding this feature

**Comment by nojvek** [comment]
I definitely want to learn how to add new environments so please keep me in
loop and let me know how I can help.

**Comment by yashpatel5400** [comment]
Alright, so there's two main problems involved here:
1) The more "computer-sciency/programming" problem of getting a system that allows communication to an emulator system
2) The more "machine learning" problem of finding a way to pose the problem as a reinforcement learning problem

I think the first should be fairly straightforward, and I'll try working on that. We should actually be able to make a way to (hopefully) do general emulation of video games now that wasm's (Web Assembly) becoming supported in browsers. Once we do that, however, we'll have to introduce a generic way that people can define "score" functions, since that will vary from game to game. There's a _lot_ of games where I imagine that being near impossible (i.e. story based games would be **extremely** difficult to pose as a reinforcement learning problem), but I guess that would fall as a responsibility of the end user.

**Comment by nojvek** [comment]
I think there are a ton of games in NES that aren't story based and that
would be a great start.

Regarding scoring functions, I agree there will be some amount of digging
around but we should be able to find memory spots where the score is kept
and read that out.

I believe that is how atari works right?

**Comment by yashpatel5400** [comment]
Yeah true, that'd be sweet. I'm trying to figure out how to get an emulator to run natively in the browser -- seems like a separate project that could be cool to tie into this one

**Comment by nojvek** [comment]
https://github.com/bfirsh/jsnes/blob/master/README.md

Jsnes?

**Comment by scientist1642** [comment]
There has been tried this - https://github.com/ppaquette/gym-super-mario
and it uses fceux  - a well known emulator. I think it should be fairly easy to package it as docker container for universe.

I was looking for ways to make something work as atari_py, which will only use cmake and be fast. so basically to integrate it with gym not universe.

**Comment by codescv** [comment]
Hi guys, I am recently working on adding NES games(fceux) to gym.
Basically I took some great ideas from gym-super-mario and made it easy to integrate other games.
Right now there is only one game, but new games can be easily added.
If anyone is interested, please take a look:

https://github.com/codescv/nesgym

**Comment by nojvek** [comment]
This is awesome. Do you imagine this be part of universe repo when you're
done?

Or will user have to do another pip install?

**Comment by codescv** [comment]
@nojvek
I am not sure whether it fits in the universe repo, since it works more in the atari-py way (by controlling the emulator directly), not the vnc way.

For the moment this is pretty much a WIP and we need to add some more games. So any suggestions and pull requests (especially about games and game memory locations to get rewards) are welcome!
