### ISSUE TITLE
Open Sourcing Universe's Gym Envs

### ISSUE THREAD

**Issue by zzh8829** [openai/universe#188]
I found the client side source code of FlashGame / World of Bits etc in their Docker images. However, they are not available anywhere online. Is there plan to open source related client (or server) sided code? I had a hard time writing new universe environments without any reference implementation, the code in docker images really helped my project.

**Comment by gray-m** [comment]
Hi, I'm having similar issues. I tried to implement my own environment in gym and integrate it into the universe.gym-core runtime, but I could not find any documentation to help me. I tried deriving a Docker image from the gym-core one and then replacing some files, namely the gym and universe installations as well as /app/bin/play_core_envs.py. In the gym and universe code, I registered my environment, and in the play_core_envs file, I changed some conditionals that were in place to make certain environments (CartPole and Atari) valid so that mine would not cause errors. However, upon making those changes, the created Docker container crashes without any useful error output. I would appreciate any help.

**Comment by UsaidPro** [comment]
Do you remember where was the source code for the client side in the Docker images @zzh8829 ? I'm trying to find the source code myself and have located the source code for the flash games themselves, but not the source code to calculate rewards, steps, etc. I know that this is late, but it would be nice to have this information somewhere on the Internet. Thanks!

**Comment by zzh8829** [comment]
@UsaidPro Apologize for this very late response, I hope this is still helpful to you or maybe other people. The docker image I was talking about is hosted on [quay](https://quay.io/repository/openai/universe.flashgames), you can find other images on there too. For the flash game specifically, the source code can be found in the /app/universe-envs directory which contains runtime for VNC, chrome browser, reward calculation and other environmental setups.
