### ISSUE TITLE
What are the future plans for Universe?

### ISSUE THREAD

**Issue by crci** [openai/universe#190]
Hi,

I just saw this tweet by @gdb https://twitter.com/gdb/status/879540368995303424 "The VNC envs **were** a useful stepping stone towards the Universe idea. Glad to see others working on next gens of these envs (we are too!)."

So, could you guys give us some update regarding the future plans for Universe? Do you plan to publish the integration tools? Do you plan to keep maintaining/upgrade this repo?

Thank you.

**Comment by gdb** [comment]
We won't be maintaining this specific repo beyond the level we have for the past few months. Since this is research software rather than anything production, there's no particular need for a migration path off it. We're working on a new set of environments, though no specific timeline on when we'll OSS them.

Would recommend checking out https://github.com/unixpickle/muniverse — looks like a great project!
