### ISSUE TITLE
may I run first sample code but container on EC2 instance?

### ISSUE THREAD

**Issue by jomyhuang** [openai/universe#80]
I'm tired pull quay.io image and maybe fetch flash game data too slow from China. can any suggest how to run by AWS EC2 instance? or other solutions?

**Comment by nottombrown** [comment]
Currently we only support pulling envs from quay.io. We will release our environments as a github repo, but do not yet have a set date for when.

**Comment by jomyhuang** [comment]
sorry, 
may I run all env on AWS EC2 instance? or run code in locally and remote container on EC2?

**Comment by tlbtlbtlb** [comment]
It needs high bandwidth between the environment container and your agent code, because it sends the screen pixels 10-60 times per second. So if you have a slow network it probably won't work.

It works well to run both agent and environment on EC2. That's how we usually do it here.

You might try downloading the image overnight. It is 1.5 GB, similar to a movie. You can run it manually with
```
docker pull quay.io/openai/universe.flashgames:0.20.15
```
